### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#146]
We don't have release version for Open3D. On the document page, it says 0.1 dev but Github repo doesn't release version. As Open3D grows, it would be good to have version if we set milestone.

**Comment by qianyizh** [comment]
I actually think 0.1 dev is the right version for Open3D as of today (2/8/2018). It has a very limited set of functionalities but the basics are there (especially for 3D point clouds and 3D SLAM). I'd like to let the community test it and tell us what are the biggest and most common interest so that I know how to plan for features of the next milestone. When Open3D has been thoroughly tested and used in both academic and industrial projects, we can call it version 1.0.

As a side note, I have high expectation about the potential of Open3D. I talked with some of my friends and they think 3D data is very useful in important (and hot) applications such as autonomous driving. Open3D has potential to support it. I can see a big potential market.

**Comment by syncle** [comment]
Released v0.1-dev. See [https://github.com/IntelVCL/Open3D/releases/](https://github.com/IntelVCL/Open3D/releases/). 
I also hope Open3D would grow and be used for many fields/areas. Closing issue.
