### ISSUE TITLE
ChangeConsoleColor and ResetConsoleColor are neither static nor exported

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#151]
`ChangeConsoleColor` and `ResetConsoleColor` are neither `static` nor accessible from
the outside.

The same applies to the function `PrintConsoleProgress`.

https://github.com/IntelVCL/Open3D/blob/347de9058eaa04a2e27fee00cc9f3d8e01f3b324/src/Core/Utility/Console.cpp#L67

https://github.com/IntelVCL/Open3D/blob/347de9058eaa04a2e27fee00cc9f3d8e01f3b324/src/Core/Utility/Console.cpp#L89

https://github.com/IntelVCL/Open3D/blob/347de9058eaa04a2e27fee00cc9f3d8e01f3b324/src/Core/Utility/Console.cpp#L110

**Comment by qianyizh** [comment]
@csukuangfj can you elaborate the use case when these functions need to be called?

I think I intentionally hide them in the unnamed namespace so that they can only be called internally from console.cpp. This avoids polluting the global ``three::`` namespace.

The unnamed namespace idea is from [Google C++ coding guide](https://google.github.io/styleguide/cppguide.html#Unnamed_Namespaces_and_Static_Variables).

**Comment by csukuangfj** [comment]
@qianyizh thank you for the reply.

As far as I know, if a function is not going to be called outside from
the .cpp file, it should be declared as static.

I find these three functions are only called inside Console.cpp, so it
should be declared as `static`. That is why I proposed the pull request.

**Comment by qianyizh** [comment]
Actually as long as it is in an unnamed namespace they don't need to be static.
Read this:
https://google.github.io/styleguide/cppguide.html#Unnamed_Namespaces_and_Static_Variables

**Comment by qianyizh** [comment]
I am closing this because I don't think the change is necessary.
But thanks for the discussion. This is helpful.
