### ISSUE TITLE
How to set mesh triangles' opacity

### ISSUE THREAD

**Issue by godspeed1989** [IntelVCL/Open3D#155]
Hi,
Thanks for the great library. I have two questions.

1) How can we set mesh triangles' opacity and visualize it?
2) How can we draw line between vertices and visualize it?

Thanks

**Comment by qianyizh** [comment]
We don't convenient opacity function yet. The reason is that OpenGL opacity is a bit hacky. Even with an alpha channel, OpenGL runs depth test as usually so you are not really able to see through the triangles. The way of rendering semi-transparent objects is usually by drawing them layer by layer, which is out of the scope of Open3D convenient functions.

To enable opacity, the best way is to change the ``GeometryRenderer`` class in:
https://github.com/IntelVCL/Open3D/blob/master/src/Visualization/Shader/GeometryRenderer.cpp

To draw wireframe, just press "w" in the visualizer window. It will show.

**Comment by godspeed1989** [comment]
Thank you very much!

**Comment by shijianjian** [comment]
Any updates in this? I believe this can be a useful feature to have.

**Comment by errissa** [comment]
@shijianjian Please see #4060 . You can use the `base_color` parameter of `MaterialRecord` to set a color with alpha.

**Comment by shijianjian** [comment]
> @shijianjian Please see #4060 . You can use the `base_color` parameter of `MaterialRecord` to set a color with alpha.

Great. I have managed to make it work. However, not sure if it is on purpose, I found that the ```base_color``` only worked on the alpha channel. For the main body color, I still need to use `paint_uniform_color`.

**Comment by errissa** [comment]
The final rendered color will be the `base_color` multiplied by the per-vertex colors which can be set by `paint_uniform_color`.  We do not currently support per-vertex opacity which is why `paint_uniform_color` only takes RGB. So, you are correct that opacity comes from the `alpha` of the `base_color`. However, it shouldn't be necessary to use `paint_uniform_color` -  with 0.14.1 the default color is white if no other per-vertex color is set so `base_color`*white is always just `base_color`.

**Comment by shijianjian** [comment]
> The final rendered color will be the `base_color` multiplied by the per-vertex colors which can be set by `paint_uniform_color`.  We do not currently support per-vertex opacity which is why `paint_uniform_color` only takes RGB. So, you are correct that opacity comes from the `alpha` of the `base_color`. However, it shouldn't be necessary to use `paint_uniform_color` -  with 0.14.1 the default color is white if no other per-vertex color is set so `base_color`*white is always just `base_color`.

Thanks for explaining. I am currently under the version of 0.14.1. If the paint_color is not set, it will give a random color disregard of the base_color.

**Comment by errissa** [comment]
Can you post an example script or sample code that demonstrates the issue?

**Comment by shijianjian** [comment]
@errissa  Sorry, you are right. It is probably because of the default color that brought by the PLY file directly.

**Comment by TheTomer** [comment]
> > @shijianjian Please see #4060 . You can use the `base_color` parameter of `MaterialRecord` to set a color with alpha.
> 
> Great. I have managed to make it work. However, not sure if it is on purpose, I found that the `base_color` only worked on the alpha channel. For the main body color, I still need to use `paint_uniform_color`.

I'd appreciate an example as well, if you can share one.

**Comment by iamsiddhantsahu** [comment]
> We don't convenient opacity function yet. The reason is that OpenGL opacity is a bit hacky. Even with an alpha channel, OpenGL runs depth test as usually so you are not really able to see through the triangles. The way of rendering semi-transparent objects is usually by drawing them layer by layer, which is out of the scope of Open3D convenient functions.
> 
> To enable opacity, the best way is to change the `GeometryRenderer` class in: https://github.com/IntelVCL/Open3D/blob/master/src/Visualization/Shader/GeometryRenderer.cpp
> 
> To draw wireframe, just press "w" in the visualizer window. It will show.

Where in the [GeometryRenderer](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/visualization/shader/GeometryRenderer.cpp) needs to be edited to accommodate the opacity functionality to `paint_uniform_color()`? For instance, `paint_uniform_color(128, 128, 128, 200)`.

**Comment by bayesian-mind** [comment]
Checkout - https://github.com/isl-org/Open3D/issues/2890.
