### ISSUE TITLE
Limitations of the function FilterImage

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#175]
See the code
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/Image.cpp#L219-L226

It supports only image with a single channel.

However, it is called by `FilterRGBDImagePyramid`
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/RGBDImage.cpp#L31-L47

How can `FilterImage` be applied to the `color_level` image with 3 channels?

**Comment by syncle** [comment]
@csukuangfj: Image module handles single channel images. Factory function for image transforms a RGB image into a gray-scale image prior to enter these functions. Strictly speaking, ``RGB`` and ``color`` would be ``intensity``, but we decide to use these word because the core intension of image module in Open3D is for RGBD image odometry.

**Comment by csukuangfj** [comment]
@syncle 
In that case, there is no use for providing the option `convert_rgb_to_intensity`
in the following functions, since set it to `false` does not work and it MUST be true.

https://github.com/IntelVCL/Open3D/blob/a703d41826cb64e31a774fa79fba13276bc96d6b/src/Core/Geometry/RGBDImage.h#L55-L79

**Comment by qianyizh** [comment]
``convert_rgb_to_intensity`` was my change. I needed a function that reads a colored RGBD image so that it can be used in integration.

You can see the blame of the file:
https://github.com/IntelVCL/Open3D/blame/a703d41826cb64e31a774fa79fba13276bc96d6b/src/Core/Geometry/RGBDImage.h#L55-L79

But for the main usage of RGBD image (i.e., odometry), RGBD images are treated as intensity-D images. This is the common practice in many papers.

**Comment by csukuangfj** [comment]
@qianyizh 

I see, thank you for the explanation.
