### ISSUE TITLE
Error for computing eigenvectors in the function FastEigen3x3

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#189]
See the code
https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/EstimateNormals.cpp#L69-L71

The code assumes that the first column of the matrix 

(A-alpha1\*Identity()) \* (A-alpha2\*Identity())

is an eigenvector corresponding to the eigenvalue alpha3.

However, this is not always the case. As described in the following address
https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/EstimateNormals.cpp#L41-L42

>Thus the columns of the product of any two of these matrices will contain an eigenvector for the third eigenvalue. 

It says the eigenvector is contained in the columns. Not every column of the matrix is an eigenvector. And not the **first** column **MUST** be an eigenvector.

An example is given  following the above statement:
```
A = 
3 2 6
2 2 5
-2 -1 -4
```

We can see that (A+I)(A-I) contains a column of all zeros.

The current implementation only considers the first column, which may be 0.
Thus it misses the true eigenvector residing in the second or the third column.

**Comment by csukuangfj** [comment]
I find that the following code
https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/EstimateNormals.cpp#L113-L115

is an elegant solution.

Are there any reasons to use own private solution?

Are there benchmarks to show that the private implementation is superior to the Eigen implementation?

**Comment by syncle** [comment]
You are right for general A matrix, but these private functions are specialized for covariance matrix. As Covariance matrix C is symmetric, so the first column of (C+I)(C-I) cannot be zero if first column or row of C is not zero. This is not happen except for the case there is no adjacent points. Open3D does not compute normal if there is no adjacent point. 

The fancy commented line was the original code, but it is replaced with private functions because they are much faster. You can notice the difference with point cloud with millions of points.

**Comment by qianyizh** [comment]
``Eigen::SelfAdjointEigenSolver<Eigen::Matrix3d>`` is slower than ``FastEigen3x3`` to an order of magnitude.

``FastEigen3x3`` assume ``A`` is a covariance matrix. The implementation works in this case.
