### ISSUE TITLE
Missing python3-dev dependency

### ISSUE THREAD

**Issue by caselitz** [IntelVCL/Open3D#209]
When compiling Open3D I got multiple errors like: `Open3D/src/External/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory`

I'm on Ubuntu 16.04 and it seems I had to install `python3-dev` to fix this. Maybe this dependency should be added to the [install-deps-ubuntu.sh](https://github.com/IntelVCL/Open3D/blob/master/scripts/install-deps-ubuntu.sh).

**Comment by rukie** [comment]
The 'optional' python binding works with both Python 2 and Python 3. I don't know that the authors are looking to fool proof everything, but it is possible it could ask if you want python bindings and with which version, then install those dependencies too.... 

Instead, maybe python bindings should be disabled by default?

**Comment by caselitz** [comment]
Hm, first thing I tried when I encountered the compilation error was to install `python-dev` - not sure why it didn't help...

Even though this is super straight forward to fix by the user, I feel compilation should work "out of the box" on a virgin Ubuntu (especially if there is already a dedicated script that installs dependencies). But this is up to the authors, I just wanted to drop a note.

**Comment by syncle** [comment]
Thanks @rukie @caselitz for the discussion.
This is another case of python binding. I put **pybind** for these questions. FYI, please see [previous questions](https://github.com/IntelVCL/Open3D/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Apybind+).


> Instead, maybe python bindings should be disabled by default?

We are maintaining CI for testing python binding using virgin Ubuntu. If there is single Python installed, and CMake does not confused, the python binding compilation should work out of box. We hope to keep python bindings by default as we have series of documents for Python API.

**Comment by rukie** [comment]
I figured the python binding was important (I certainly like it!). 

I've been looking over shell scripts and maybe the ubuntu install could 
' 
#!/bin/sh

set -ev

# install OpenGL, for GLFW
sudo apt-get install xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libg$

while true; do
    read -p "Do you wish to install with Python 2 or 3 dependencies?" yn
    case $yn in
        [2]* ) sudo apt-get install python-dev; break;;
        [3]* ) sudo apt-get install python3-dev; break;;
        * ) echo "Please answer 2 or 3.";;
    esac
done
'
I don't exactly care for how 'primitive' it feels... in the spirit of open source maybe I'll dig into this a bit more and see if there's a way to update the cmake file with the desired binding too.

**Comment by qianyizh** [comment]
This is good discussion.

I had problems with python bindings on Ubuntu myself. Part of the reason is that the python ecosystem is a bit chaotic. On Ubuntu there are python2 and python3. Many use integrated environments such as anaconda. There are also different package management tools such as ``conda`` and ``pip`` and they do not work very well together. The problem on windows system is even worse.

Open3D uses pybind11 as its python binding. But pybind11 has difficulties finding the "right" python of the system. Often, the user has to specify ``cmake -DPYTHON_EXECUTABLE:FILEPATH=<path-to-python-executable>``, which is both documented in [Open3D doc](http://open3d.org/docs/compilation.html#python-binding) and [pybind11 doc](http://pybind11.readthedocs.io/en/stable/faq.html). This is a really annoying drawback. But I don't have any good idea to deal with it - especially when you have run a Ubuntu system for a long time and have messed up with lots of python environments.

I have a script in one of my personal repo that uses Open3D. I am posting it here just for reference if anyone is interested (I use anaconda3 so the default path is set to it):
```
export PYPATH="~/anaconda3/bin/python"
echo "==== setup open3d ===="
read -e -p "Compile open3d from source [y|n]? " -i "n" OPEN3D_YN
if [ $OPEN3D_YN = "y" ]
then
  echo "You need edit this script to specify your python executable location."
  read -e -p "Enter python path: " -i $PYPATH PYPATH
  echo "Set python executable path at $PYPATH"
  cd open3d
  mkdir build
  cd build
  cmake ../src -DPYTHON_EXECUTABLE:FILEPATH=$PYPATH
  make -j
  cp lib/*.so ../../ext_mods/
  cd ../../
fi
echo ""
```

Back to the issued raised by OP, I think the point that "Open3D should work out-of-the-box with a vanilla Ubuntu" is valid. The easiest fix seems to be adding both ``python-dev`` and ``python3-dev`` in the install shell. Thanks @rukie to provide a selection option, but I think adding both seems to be the easiest way.
