### ISSUE TITLE
cmake error on windows

### ISSUE THREAD

**Issue by chouspy** [IntelVCL/Open3D#228]
CMake Error at External/pybind11/CMakeLists.txt:72 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.

**Comment by chouspy** [comment]
with cmake3.11.0+python3.6.3+visual studio 2017 when tick the option PYBIND11_TEST

**Comment by syncle** [comment]
This is because we omit `tests` folder from pybind, but `CMakeList.txt` is untouched. If `PYBIND11_TEST` flag is `OFF`, it should not include tests folder. 

Depends on cmake version, I sometime found cmake still trying to check all sub folders although `add_subdirectory` is not reachable. If it is the case, Can you delete following lines and see that resolves the issue?

https://github.com/IntelVCL/Open3D/blob/daa0e01e09533ecccfab613a9bb6577de892e89a/src/External/pybind11/CMakeLists.txt#L71-L73

**Comment by chouspy** [comment]
thanks, your aid really helped me
