### ISSUE TITLE
How to contribute c++ tutorials to the repository?

### ISSUE THREAD

**Issue by dotchang** [IntelVCL/Open3D#234]
Hi, developers.

I translated some python adovanced-tutorials into c++. Please, refer to
http://cvl-robot.hateblo.jp/entry/2018/03/02/181941

I would like to contribute it to the repository, but I have 2 questions.
1. Which directory is correct?
2. Which filename is correct?
Temporarily, I put it into the Test directory, and named TestColoredPointRegistration.cpp to be decided according to colored_point_registration.py.

Please let me know some advice.

**Comment by qianyizh** [comment]
This is great!

I think we can have a folder named ``Tutorial`` under ``src``, with a similar subfolder structure as ``src/Python/Tutorial``. You can remove ``Test`` words from the filename as well. E.g., ``ColoredPointRegistration.cpp`` would be fine.

Wrt document, can you contribute a document describing how to use CMake to compile a separate cpp file and link to Open3D? Maybe put it under ``docs/tutorial/Basic``

**Comment by dotchang** [comment]
I will add a new directory /src/Tutorial/Advanced and some files, such as ColoredPointRegistration.cpp, etc.

> CMake and documents
Maybe, it's difficult for me, but anyway I will try it.

**Comment by dotchang** [comment]
I wrote a CMakeLists.txt for independent cpp file on my environment, and it works.
https://github.com/dotchang/Open3D/tree/master/src/Tutorial/Advanced
But, to write CMakeLists.txt for every environment is so difficult work for me due to lack of knowledge.
Could you help me?
At first, I want to brush-up it for linux environment.

1. How can I find a path for Open３D?
Currently, I used "set" command and gave an absolute path directly.
like this, set(Open3D_DIR "/home/cvl/workspace/Open3D")

2. How can I detect PNG16 instead of PNG12?
find_library or FindPNG gives PNG12(which is installed for system environment).
I ignore it and gave an abosolute path.

3. When I use native installed jsoncpp, OpenGL and jsoncpp shows unsure behavior in link process.
To solve this problem, I called jsoncpp twice, like this. 
target_link_libraries(${PROJECT_NAME} ${JSONCPP_LIBRARIES})
target_link_libraries(${PROJECT_NAME} ${OPENGL_gl_LIBRARY})
target_link_libraries(${PROJECT_NAME} ${JSONCPP_LIBRARIES})

Can you give me your opinion?

**Comment by syncle** [comment]
> How can I find a path for Open３D?
Currently, I used "set" command and gave an absolute path directly.
like this, set(Open3D_DIR "/home/cvl/workspace/Open3D")

This issue is related to #130. We are working on this issue. The output for #130 would be findopen3d.cmake. This will allow ``find_package(Open3D)`` and make things much easier.

> How can I detect PNG16 instead of PNG12?


Please check out this:
https://github.com/IntelVCL/Open3D/blob/c9aab50f15e74aaaa9c30e190a143340d9a1a3ec/src/External/CMakeLists.txt#L32

> When I use native installed jsoncpp, OpenGL and jsoncpp shows unsure behavior in link process.
To solve this problem, I called jsoncpp twice


This is bit weird. Actually you won't eventually have to manually add all the dependencies for compile tutorial. Instead, it should look like [this style of cmakelist](https://github.com/dotchang/Open3D/blob/master/src/Tools/CMakeLists.txt).

We will share updates soon.

**Comment by dotchang** [comment]
Thank you for your kind reply!
I misunderstood meaning of "to compile a separate cpp file".
I update the CMakeLists.txt to [the style of cmakelist](https://github.com/dotchang/Open3D/blob/master/src/Tools/CMakeLists.txt).

**Comment by syncle** [comment]
Awesome! Thanks @dotchang.

**Comment by syncle** [comment]
Closed via #247.
