### ISSUE TITLE
remove 3rdparty folder

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#238]
I propose we remove the src/External folder.
I want to avoid any future confusion if other projects will have to use some of the same external dependencies. It is good practice to reuse those dependencies across many projects rather than duplicating the code for each project.

Some of these dependencies belong to existing git repositories so it should be easy to pull the necessary version when building Open3D.

For other dependencies we can instead create mirror repositories (fork) under our team's umbrella and use proper versioning to match the original source. In this case we can match master to the progress made by the original teams and create our own branches when we want to fix/extend the code ourselves.

**Comment by qianyizh** [comment]
The main purpose of ``src/External`` is to make Open3D Windows-friendly. I still want to keep it so that Windows users can just pull the repo and compile Open3D out of the box.

I think your proposal is to use ``git submodule`` to replace the hard copies of the external libraries. This is a good suggestion. I thought about this. There are pros and cons.

Pros as mentioned in OP: it is cleaner, easier to use across projects, and easier to track the latest versions.

Cons: it is harder to track the exact version we need. ``submodule`` can track the exact version we need. But I had the experience that I had to edit some files (e.g., the CMake file) or fix some hot bugs (submitted to the official repo but could not wait until PR gets merged). In these cases, it is always better to have my own version of the library. Thus it is either a hard copy in ``src/External`` or a fork of the original repo. I chose the former because it reduces the maintenance cost from my side, :)

I dislike ``src/External`` too. I am open for discussions of a better solution of this.

**Comment by syncle** [comment]
One suggestion is to maintain another repo just for Open3D dependencies. That repo is just tested for Open3D. This will make Open3D repo much compact.

**Comment by syncle** [comment]
Just for update ``src/External`` folder is moved into ``3rdparty`` folder.

**Comment by qianyizh** [comment]
The discussion is followed up on discord channel and offline discussions. Feel free to hop in and contribute your thoughts. https://discord.gg/qsm2fd

**Comment by syncle** [comment]
Addressed in #725.
