### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#256]
My current implementation is about 3.8GB:
- lxde based
- apt upgrade
- installed debug tools

The above options do take a lot of space.
A previous implementation used less than 1.5GB with some more or less obvious caveats.
- ratpoison based 
- no apt upgrade
- no debug tools
- no editing tools

Caveats of the second approach:
- simpler window management 
- any installs in the container are not persistent so restarting requires installing those apps again.

**Comment by takanokage** [comment]
An idea is to look into providing the option to perform headless from the terminal only with no support for vnc/window management/interactive GUI. This has the potential of keeping the image super light-weight.

**Comment by takanokage** [comment]
oops, the Dockerfile proxy settings are only valid on my particular computer.
I need to remove them before the integration.

**Comment by syncle** [comment]
This issue is related to #262.

**Comment by syncle** [comment]
Closing this issue as #262 is closed for now.

**Comment by plusk01** [comment]
Just to add an update: I attempted to build open3d using the `python:3.9-alpine3.13` base docker image - I made some progress, but as @takanokage suggested it got pretty complicated and I had to move on. Maybe this will be useful for the next attempt

```Dockerfile
FROM python:3.9-alpine3.13

RUN apk update && apk upgrade && \
    apk add --update --no-cache \
        build-base \
        cmake \
        eigen-dev \
        git

RUN cd /tmp && \
    git clone -b rspd --recurse-submodules https://github.com/plusk01/Open3D && \
    mkdir Open3D/build
    # mkdir Open3D/build && cd Open3D/build && cmake -DBUILD_EXAMPLES=OFF .. && \
    # make -j$(nproc) && make install-pip-package -j$(nproc)

RUN apk add --update --no-cache \
    libx11-dev \
    xrandr \
    libxrandr-dev \
    glu \
    glu-dev \
    glfw \
    glfw-dev \
    libxcursor-dev \
    clang \
    clang-dev

# the next line breaks, so i would drop into a /bin/sh at the previous successful layer and try things
RUN cd /tmp/Open3D/build && cmake -DBUILD_EXAMPLES=OFF -DBUILD_FILAMENT_FROM_SOURCE=ON .. && make -j$(nproc)
```

notes:

- pre-built filament uses glibc -- alpine uses musl, so [this line](https://github.com/plusk01/Open3D/blob/master/3rdparty/filament/filament_download.cmake#L31) fails
    - in alpine, `ldd --version` says
   ```
    ldd --version
    musl libc (x86_64)
    Version 1.2.2
    Dynamic Program Loader
    Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
    ```
    - so I set `-DBUILD_FILAMENT_FROM_SOURCE=ON`
 - because musl is used, 3rdparty/tbb breaks
     - see https://github.com/oneapi-src/oneTBB/pull/203
     - also relevant [this](https://gitlab.alpinelinux.org/alpine/aports/-/blob/9ccebbf79be1958741f1905c6bf3e2a0400bcc92/testing/libtbb/musl.patch) and [this](https://community.intel.com/t5/Intel-oneAPI-Threading-Building/Building-on-musl-libc/td-p/996089)

finally, filament fails with

```bash
-- Build files have been written to: /tmp/Open3D/build/filament/src/ext_filament-build
[ 20%] Performing build step for 'ext_filament'
Scanning dependencies of target gtest
[  0%] Building CXX object third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o
In file included from /tmp/Open3D/build/filament/src/ext_filament/third_party/libgtest/googletest/src/gtest-all.cc:38:
/tmp/Open3D/build/filament/src/ext_filament/third_party/libgtest/tnt/../googletest/include/gtest/gtest.h:55:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
```

i.e., clang's libc++ headers can't be found.

Note that I tried removing `NO_DEFAULT_PATH` from [this line](https://github.com/plusk01/Open3D/blob/4950cb46b898a5dc035e3bd2a00e08a988cfb3a7/3rdparty/find_dependencies.cmake#L964) to try and get clang to use libstdc++ instead of the missing libc++ (I also `set(CPPABI_LIBRARY "")` since g++ doesn't let you specify the ABI [<- not sure if true statement])

Ultimately, this seems like the next roadblock - [no full support](https://gitlab.alpinelinux.org/alpine/aports/-/issues/7872) for clang / libc++ in alpine? Maybe need to build clang from source to get libc++ and libc++abi?
