### ISSUE TITLE
Improving reconstruction system

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#287]
Open3D's reconstruction system is implementation of the paper [Park et al., Colored Point Cloud Registration Revisited, ICCV 2017](http://redwood-data.org/indoor_lidar_rgbd/paper.pdf). For the results in the paper, we used OpenCV + PCL + g2o. As we re-implemented the algorithm from scratch, Open3D's reconstruction system produces other results. I got a request that Open3D's implementation needs some improvement.

To list a few:
- [x] Multi-threading is not fully working.
- [x] improving reconstruction quality.
- [x] there is a weird behavior when building a fragment.

**Comment by Sahloul** [comment]
@syncle Well, if you have both implementations, then how about debugging intermediate steps in both of them to figure out where is the glitch? If you can pinpoint the issue source, maybe we can help further.

Another suggestion besides the [RANSAC upgrade suggestion](https://github.com/IntelVCL/Open3D/issues/288#issuecomment-380980025), is to implement the SLAC (issue #143), which should improve the quality greatly!

**Comment by syncle** [comment]
Thanks for the suggestion. This issue is privately raised by @awchen, and he is working for this issue.

**Comment by qianyizh** [comment]
Also FYI, in Park2017, I fixed a bug and improved SLAC.

It's actually silly: the data term in SLAC objective should be point-to-point distance instead of point-to-plane distance. The reason is that ICP (point-to-plane or Park2017) has already done a great job in pairwise registration and the correspondences found after pairwise registration can be considered genuine. Thus using point-to-point distance won't hurt. In contrast, using point-to-plane distance allows surfaces to slip along planes, which may cause issues in global alignment.

**Comment by syncle** [comment]
Update: the dataset released on http://redwood-data.org/indoor_lidar_rgbd/download.html were raw color and depth frames, and it was not synchronized. Direct applying those raw frames to reconstruction system induce severe distortion. At this point, users got confused. I had updated the dataset. This resolves **there is a weird behavior when building a fragment.**
