### ISSUE TITLE
Unable to build shared libraries

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#290]
The current cyclic dependency between the IO and Core libraries prevent building shared libraries!
This is a bad design issue, and it should be addressed. The user should be able to build static or dynamic libraries.

Although it mostly applies for other platforms, when compiling on Windows with MSVC using `set(Open3D_LIB_TYPE SHARED)`, I got:
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "Core" of type SHARED_LIBRARY
    depends on "IO" (weak)
  "IO" of type SHARED_LIBRARY
    depends on "Core" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

**Comment by syncle** [comment]
That's interesting because `Open3D_LIB_TYPE` is `SHARED` by default and [Open3D's CI for Visual Studio](https://ci.appveyor.com/project/syncle/open3d) never complain about this. Can you tell me which Visual studio and cmake version you are using? We recommend CMake 3.0+ and Visual studio 2015 sp3 (or higher).

**Comment by Sahloul** [comment]
@syncle Maybe you got confused! The library is STATIC by default.. Double check here:
https://github.com/IntelVCL/Open3D/blob/3cbee2e1ccc0ec80ed1f031411335421f59927ea/src/CMakeLists.txt#L40

However, me, and perhaps others, want to compile it as SHARED library

**Comment by Sahloul** [comment]
@syncle Sure! I will give it a try tonight..
