### ISSUE TITLE
`three` is an inaccurate and vague namespace

### ISSUE THREAD

**Issue by ghost** [IntelVCL/Open3D#294]
The namespace `three` utilized in the C++ code does not follow the conventions!
I strongly suggest renaming it to `open3d`.

Waiting until the library gets more famous will make such changes much more harder, as it might break several user-implementations.

**Comment by syncle** [comment]
I think @qianyizh can give best answer for this.

**Comment by qianyizh** [comment]
This is a branding issue.

I debated it back and forth for a very long time. Vladlen was also part of the decision. I chose ``three`` among a few names including ``open3d``, ``o3d``, ``openthree``, etc. There are a couple of reasons.

First, I don't like the namespace name to be the same as the library name. It causes confusion. Second, I don't like numbers in the namespace name. It is ... lame. Third, the name needs to be short and easy to memorize.

I checked most of the famous libraries, ``three`` does not conflict with any of them, except ``three.js``. But ``three.js`` is a webgl library so I don't think it matters that much.

I haven't seen a big issue with ``three`` so far and personally I like it. Maybe you can convince me that it is a bad idea, 😸

**Comment by Sahloul** [comment]
Namespace is an identifier, and such identifier will be used by the users, not only by developers!
Kindly think from the user perspective! `three` is way vague and does not carry any intuation to the user.

> I don't like the namespace name to be the same as the library name

@qianyizh Do not you think your reason is very subjective?
I ask you to reconsider this decision before we fix the installation issue. It would become very hard to change it afterwards

**Comment by takanokage** [comment]
Let's revisit this topic.

**Comment by syncle** [comment]
Addressed in #500.
