### ISSUE TITLE
Tab indent vs space indent

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#308]
Open3D uses tab for the indent. 

From http://open3d.org/docs/contribute.html. 
> Use tab for indent. In IDE it should be 4 spaces wide. Use two indents for a forced line break (usually due to the 80 character length limit).

We got several requests regarding the space based indent (4 spaces) instead. Which one would be better? This issue have been discussed within Open3D admins, but we would like to listen public opinions. We are open for the either suggestions.

**Comment by Sahloul** [comment]
Being consistent is important, but following the majority of common practices is no less.

I believe many potential developers collaborate in other projects as well, and the majority of such projects utilize space indents. Thereby, it is no wonder development tools are already tuned for space indentation. It would be a real pain to switch these settings back and forth while working with different projects! Therefore, I really hope this project switches to space indents...

**Comment by qianyizh** [comment]
Haha, as the culprit of this issue, let me explain my thoughts.

I did the research three years ago when I started the project. My conclusion is the same as @takanokage . It really does not matter as long as it is consistent. There is even a big vote on stackoverflow. And it turns out all windows developers vote for tabs, all linux developers vote for spaces. And the vote result is almost even with a small margin favoring tab. So I made the call for tab at that moment.

I configured all the IDEs I have used: Visual Studio, XCode, Atom, vim... I feel the pain from both sides.

I think we can vote for Open3D too. I don't have a strong opinion myself. So I forfeit my vote. On this topic we just go with the majority preference of the developer community.

**Comment by Sahloul** [comment]
It seems that spaces already won :grin:
Do we have a consensus here?

**Comment by qianyizh** [comment]
Let's wait for another day just to let the Visual Studio users have a chance to voice their opinion before weekend!

**Comment by Sahloul** [comment]
I am using Visual Studio for this project by the way :wink:

**Comment by syncle** [comment]
I bet space indent. We have been experienced that many PR was used with spaces, and we have been asking them to use tab instead (including @Sahloul :wink:). This may not be the optimal way in a long-run.

I looked over famous repos, and checked what they are using for indent.
- OpenCV: 4 spaces
- Eigen: 4 spaces
- Tensorflow: 2 spaces
- ROS: 4 spaces

I think space gets more vote. Any famous repo that I am missing?

**Comment by Sahloul** [comment]
@syncle Yes! You forgot the famous Open3D ::wink::
It currently uses ~160,000 space indents, and ~24,000 tab indents

**Comment by syncle** [comment]
I think we need pure PR for this if we decide to switch. Let me volunteer.

**Comment by Sahloul** [comment]
@syncle OK! that is it.. You destroyed all my PRs now..
I guess I will maintain my own repository, and you guys do whatever you want

**Comment by takanokage** [comment]
@Sahloul it's not a big deal, is it? happens all the time to me as well. True, in your case there's a lot more merging to handle, let me take a look and if I manage to fix it I'll do a PR to your `enhancement/enable_installation` branch later tonight.

**Comment by takanokage** [comment]
I guess my work wasn't needed after all... (#319)
