### ISSUE TITLE
Custom CI images and parallel AppVeyor testing

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#309]
Current issues with the CI images:
- There is a need to perform `brew upgrade` to update `cloog`, `gcc`, and `python` in the Mac images
- Linux images takes a big portion of the testing time to install its requirements
- AppVeyor executes the tests in sequential order. With 4 tests, it takes more than 40 minutes

Suggestions:
- Build custom images with all dependencies already installed
- Upgrade AppVeyor to at least a premium account

**Comment by syncle** [comment]
> Build custom images with all dependencies already installed

I don't have clear answer for this, but I had tried docker based approach before (#280). If docker image is pre-built and fetched at the CI runtime, it would be working solution. Related document is 
https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry

> Upgrade AppVeyor to at least a premium account

We had subscribed travis-ci before release. Likewise, we can consider this option.

**Comment by qianyizh** [comment]
We should just upgrade.

**Comment by Sahloul** [comment]
@syncle Something like [this](https://docs.travis-ci.com/user/enterprise/build-images/) or Ducker as you said.

**Comment by takanokage** [comment]
We're fortunate to already have a docker proposal. Open3D builds and runs inside this docker container with the limitation for now that some of the saved images are black. With a few tweaks I'm sure we could use this docker solution.

**Comment by syncle** [comment]
I thought that too, but using Open3D docker image having some issues. Travis CI automatically clones Open3D repo. Fetching Open3D docker image will make duplicate Open3D copies. 

The major bottleneck is AppVeyor. Travis-CI takes approximately 10 mins because we can utilize four concurrent jobs on Travis-CI. **AppVeyor takes about 40 mins.**  This is major bottleneck. I will setup premium account. Travis-CI issue can be revisited later.

**Comment by syncle** [comment]
Configured AppVeyor premium account.
