### ISSUE TITLE
Orthographic projection in Visualizer

### ISSUE THREAD

**Issue by adamlofts** [IntelVCL/Open3D#340]
Is it possible to configure an orthographic projection? 

It is mentioned in the docs here: https://github.com/IntelVCL/Open3D/blob/35be432d45bf47bbcdf920c62d7d9d446ac6d36d/docs/tutorial/Advanced/interactive_visualization.rst#L111

**Comment by qianyizh** [comment]
Yes, in the interactive mode, press ``[`` until the view does not change, it is the orthogonal projection.

Under the hood, ``[`` reduces ``field_of_view`` and ``]`` increases it. Once ``field_of_view`` is too small (we set it to 5 degrees), we use orthogonal projection instead of perspective projection.

**Comment by adamlofts** [comment]
Thanks for the help!

**Comment by samarth-robo** [comment]
Is there way to do this through Python code?

**Comment by syncle** [comment]
Got it. Let me working on this request.
