### ISSUE TITLE
installing open3d python

### ISSUE THREAD

**Issue by annacesar** [IntelVCL/Open3D#425]
Hi,

I have tried to install open3d python with
pip install open3d-python

but when I import the package in my spyder environment, I get an error ('DLL load failed')

from open3d import *

How can I solve the issue?

**Comment by syncle** [comment]
We are addressing this issue in #408. A quick work-around is to build from source with the dependent libraries.

**Comment by takanokage** [comment]
This is a feature request not a bug.
If we agree that solving #430 would also address this one I would vote for closing #425.

**Comment by syncle** [comment]
This issue is addressed with Open3D v0.3 release. 

@annacesar: Let me close the issue. Please try ``pip install open3d-python`` or ``conda install -c open3d-admin open3d``. Details are in [here](http://www.open3d.org/docs/tutorial/Basic/python_interface.html#install-open3d-from-pypi). Feel free to reopen this if necessary.
