### ISSUE TITLE
Question: Combine transformations

### ISSUE THREAD

**Issue by rukie** [IntelVCL/Open3D#463]
Let's assume I have 30 frames of continuous data. I have 3 "fragments" that are assembled from 10 frames each. I know the transformation of frame 0-9, 10-19, 20-29. Each of these fragments assumed every frame starts at x,y,z of 0,0,0.

When I go to combine fragment 0, 1, and 2 I can assume that the initial transformation of fragment 1 is the last transformation of frame 0-9 in fragment 0. When I attempt to create the initial transformation for fragment 2, it will be a combination of the last transformation of 0-9 and the last transform of 10-19. 

I know I can apply the two transformations one after another, but I'd rather "combine" the transformations. Is this simply a matrix multiplication? Or is there something more advanced I need to be aware of? I hope my question is clear enough.

**Comment by syncle** [comment]
Yes. It is matrix multiplication. 

As a quick answer, this is implemented in this tutorial. http://open3d.org/docs/tutorial/ReconstructionSystem/integrate_scene.html#integrate-rgbd-frames

Take a look at this line:
```
            pose = np.dot(pose_graph_fragment.nodes[fragment_id].pose,
                    pose_graph_rgbd.nodes[frame_id].pose)
```
It multiplies matrices (note: you will have to use numpy.dot instead of '*' operator. '*' is element-wise matrix multiplication) to make a global, accumulated pose. 

Let's say the transformation from fragment to fragment is T^frag_ij and frames to frame is T^frame_ij, the absolute, accumulated pose would be ``T^frag_ij x T^frame_ij`` where ``x`` is matrix multiplication.

**Comment by rukie** [comment]
Thank you for clarifying!

**Comment by baptiste-mnh** [comment]
Hi,
I'm not sure to understand .
I have 3 cameras in a column(let call them n° 1, 2 and 3).
I successfully align:  3->2 and 2->1 (source -> target)
I want my camera 1 to be the target for the 2 and the 3.

How to get the matrix to directly align the camera 3 on the camera 1 . I tried to multiply the one I get form the 3->2 registration with the 2-1 without success.

I tried to do something like this :
```
matrix_cam1 = np.identity(4)
matrix_2_to_1 = #supposing i already have it
matrix_3_to_2 = #supposing i already have it

matrix _3_to_1 = matrix_3_to_2.dot(matrix_2_to_1)
```
But the cam 1 doesn't align with cam 3 with matrix _3_to_1 ...
