### ISSUE TITLE
Shouldn't install lib/libtinyfiledialogs.a

### ISSUE THREAD

**Issue by yurivict** [IntelVCL/Open3D#569]
lib/libtinyfiledialogs.a comes from some other project. This project might be installed separately. You shouldn't install it because it might conflict with other packages.

**Comment by yxlao** [comment]
Agreed. 

If 1) we build a 3rd party lib from source 2) if the 3rd party lib is a static lib, we shall not install the 3rd party lib at `make install`. This is because the 3rd party lib is already statically linked (embedded inside) the `libOpen3D.a` or `libOpen3D.so`. 

@syncle @takanokage is this your understanding as well? If yes, i'll create a task for this.

**Comment by syncle** [comment]
Yes it is. If 3rd party library is embedded, open3d library become stand-alone. You won't need to install other libraries.

**Comment by yxlao** [comment]
Thanks @syncle, internal task created
