### ISSUE TITLE
Issue for compiling Open3D on Windows

### ISSUE THREAD

**Issue by Hao-HUST** [IntelVCL/Open3D#623]
Hi, 

Thanks for sharing your great work.

I tried to compile the Open3D on windows, based on your compiling step(http://www.open3d.org/docs/getting_started.html).

The generation of Open3D.sln from Cmake succeed and rebuilt the ALL_BUILD target, but the compiling on INSTALL is failed. My env is：Windows 10, VS2015 Update 3 and Cmake 3.12.0.

I got the following error:
![image](https://user-images.githubusercontent.com/10823967/47255083-db5c1880-d49d-11e8-8257-a5f6e97193dd.png)

Any suggestions?

Thanks again.

**Comment by Jason420Git** [comment]
This tends to happen because the default install location is in program files which requires admin permission. Either open visual studio in admin mode, or you can change the location by changing CMAKE_INSTALL_PREFIX variable. 

Be aware that the install does not separate debug and release builds, so you'll need to reinstall (once switching to release or debug) in order to update that directory with the correct libs.

**Comment by yxlao** [comment]
agreed with @Jason420Git , seems similar to https://github.com/IntelVCL/Open3D/issues/420#issuecomment-430814256

**Comment by Hao-HUST** [comment]
Thanks a lot. As you suggested, the problem is solved.

**Comment by qianyizh** [comment]
@yxlao I double checked our documents. I think we need to explicitly say that you need to run Visual Studio in administrative mode in order to compile INSTALL with default options. Can you add this to a ``tip`` or ``note`` to the document? Also I dislike the ``error`` bubbles in the doc, can we just all change them to ``note``? That would be great.
