### ISSUE TITLE
Integration Issue

### ISSUE THREAD

**Issue by Chromium97** [IntelVCL/Open3D#633]
Hello I am using intel realsense d435 to capture aligned rgb and depth images for the reconstruction of 3d human model.
The fragments that are created are good, as you can see in the images, but
the integration step is creating a bad final ply file.
I am running run_system.py config/*.json --make --register --refine --integrate.

Any Help!

Thanks!

![whatsapp image 2018-10-25 at 4 08 30 pm](https://user-images.githubusercontent.com/13464149/47495149-0b763380-d871-11e8-946e-e588ea5bf37c.jpeg)
This is integrated scene.

These are the fragments generated after running make fragments.py
![whatsapp image 2018-10-25 at 4 08 29 pm](https://user-images.githubusercontent.com/13464149/47495151-0c0eca00-d871-11e8-9770-20f1a1dc66ac.jpeg)
![whatsapp image 2018-10-25 at 4 08 28 pm 1](https://user-images.githubusercontent.com/13464149/47495154-0c0eca00-d871-11e8-893b-739719241e8e.jpeg)
![whatsapp image 2018-10-25 at 4 08 28 pm](https://user-images.githubusercontent.com/13464149/47495155-0c0eca00-d871-11e8-8290-a4fcf4a20c7b.jpeg)
![whatsapp image 2018-10-25 at 4 08 26 pm](https://user-images.githubusercontent.com/13464149/47495157-0ca76080-d871-11e8-9e23-ddf43b134846.jpeg)

**Comment by syncle** [comment]
Human scanning is interesting application, but it is bit sad the result are not good yet. 

Does the **every** fragments are looks perfect? Is there some jumps between frames? Otherwise, global registration just fails to register the thin structures. 
- Consider decrease max_depth (I think 1m is enough) and voxel size (maybe 0.03m) to be focused on the human. 
- Another trick for helping global registration is to put some object around the people :)

**Comment by Chromium97** [comment]
Thanks for reply!
Yes, every fragment looks perfect. No, there are no jumps between frames. 

- I am trying to play with different parameters, and it's giving good results for max_depth=3m and voxel _size = 0.03.

- I don't want to keep any things near the human, so can you please suggest any other things we can change in order to get the best results. I mean changing any other parameter or function.

Thanks

**Comment by syncle** [comment]
If fragment looks good, only the reason could be global registration does not work properly, or the human was not stand still and global registration was failed to find correct loop closure. If you don't like to put anything in the background I can suggest the followings:
- Try capture static object like human (mannequin or similar size object etc.) if that is reconstructed well, the root cause is the human is not static.
- Decreasing depth is necessary even if every fragments look good, because in your case, the background is homogeneous, and global registration confuses on that. Try a maximum depth something less than 3m.
- try ``"icp_method": "point_to_point"`` this will not use surface normal, so maybe more robust in your case.
