### ISSUE TITLE
Incorrect normal estimation from .ply file.

### ISSUE THREAD

**Issue by satwickdash** [IntelVCL/Open3D#646]
I am trying to estimate the normals of a face point cloud using `estimate_normals` method. But instead of the expected normals for a tangential surface at each point, all the normals are pointing towards the z-direction.

Link - [face.ply](https://gist.github.com/satwickdash/530942642d7a91e49b36a9d331a7e120)
The estimated normals look like:
![normals](https://user-images.githubusercontent.com/11016698/47632849-c3f1ef00-db71-11e8-8572-814ffa339836.PNG)

As visible, all normals point forward, instead of how we expect them to point normal to the surface. Is this correct behaviour ?

**Comment by satwickdash** [comment]
Thank you. On increasing the `radius` to 10 and `max_nn` to 30, the normals appear quite how I expected.

Also, is there a particular ratio of radius_size to max_nn, that is standardly observed ?

**Comment by syncle** [comment]
If you are using HybridSearch, max_nn is the maximum nearest neighbor to save some time - for example, once the radius search finds 30 nearest neighbors, it ignores the rest of the neighbors within the radius. It is not accurate, but you can easily set maximum upper bound for neighborhood search. 

I guess the parameters used are reasonable, because the points are regularity distributed. Keep ``max_nn`` as reasonable (number 30 seems good to me), and use the reasonable ``radius`` depending on your dataset. To visualize what is really used for normal estimation, you can visualize neighbors. [Please see this tutorial](http://open3d.org/docs/tutorial/Basic/kdtree.html) for this.

**Comment by whu-lyh** [comment]
> I am trying to estimate the normals of a face point cloud using `estimate_normals` method. But instead of the expected normals for a tangential surface at each point, all the normals are pointing towards the z-direction.
> 
> Link - [face.ply](https://gist.github.com/satwickdash/530942642d7a91e49b36a9d331a7e120)
> The estimated normals look like:
> ![normals](https://user-images.githubusercontent.com/11016698/47632849-c3f1ef00-db71-11e8-8572-814ffa339836.PNG)
> 
> As visible, all normals point forward, instead of how we expect them to point normal to the surface. Is this correct behaviour ?

hello there，i just wander is there any wrong oriention problem while you estimate the normals of face using the original "Open3D/src/Core/Geometry/EstimateNormals.cpp"?
thx
