### ISSUE TITLE
Point cloud overlapping on mesh

### ISSUE THREAD

**Issue by skylouis** [IntelVCL/Open3D#667]
Hi
I'm trying to align a point cloud file coming from depth camera to a known model in order to determine the position of the camera relatively to the model. 
I can convert the mesh model into a point cloud model in order to do the regular point cloud overlapping but by doing that i'm losing a lot information and the files i'm working on becomes heavier and more complicated to work with. 
Could you give me some advice to do that ?

**Comment by syncle** [comment]
> i'm losing a lot information and the files i'm working on becomes heavier and more complicated to work with.
I cannot get the point clearly. How did you convert a mesh into a point cloud?

**Comment by syncle** [comment]
I see. I think your approach is absolutely correct because you are sampling points from continuous surface, and ICP is made for point cloud registration. I don't have advice for now, but it might be good if you apply voxel_downsample to make sure that sampled points are uniformly distributed in the space.
