### ISSUE TITLE
Color integration in UniformTSDF only partially truncated

### ISSUE THREAD

**Issue by rpautrat** [IntelVCL/Open3D#726]
Hi, thank you for providing this nice library, it is very useful.

I have a doubt about the color rendering of the TSDF. From the line 311 and further of the file  `Open3D/src/Core/Integration/UniformTSDFVolume.cpp`, it seems that only the voxels with an sdf value greater than minus the truncation threshold are updated (as should be the case): `if (sdf > -sdf_trunc_f)`. However, shouldn't there be also another condition to restrict the voxels with positive sdf but lower than the truncation threshold? For example something looking like this: `if (sdf > -sdf_trunc_f && sdf < sdf_trunc_f)`?

This is actually not a real problem for the TSDF itself as there is a `std::min(1.0f, sdf * sdf_trunc_inv_f);` that cuts the sdf value when it is too high. But for the color integration, it means that when a colored pixel on a surface in the rgb image is seen, all the voxels on the ray between the surface and the camera are updated. Thus voxels "in the air" which should have no color get colored. Is this a normal behavior?

**Comment by qianyizh** [comment]
Yes!! This is implemented intentionally in this way. The reason is that RGB-D images are noisy and contain outlier pixels. They may become floating points here and there. For example, in the following setting, when camera is at ``camera1``, it may create an ``outlier point`` from sensor noise.

```
Camera1                                                       Surface
                                                              Surface
                                                              Surface
                                  outlier point               Surface
Camera2                                                       Surface                  
```

If the TSDF is strictly truncated (using ``if (sdf > -sdf_trunc_f && sdf < sdf_trunc_f)``, there is no way to prune these ``outlier point``s. However, if in ``camera2``, this outlier point does not exist, it can be pruned with criteria ``if (sdf > -sdf_trunc_f)``. Basically, if a camera sees a surface, we should trust that on the ray from the camera to the surface, there is only "empty space".

In my implementation, I tried multiple settings, and finally decided to use this one as it is the most robust and produces the best results.

For the coloring part, I guess it does not matter since the voxels in the air won't get reconstructed anyways. So the color should not leak - at least I have not observed in any case yet.

**Comment by rpautrat** [comment]
I see, thanks a lot for the detailed explanation! Indeed, for the color one can always use only the points on surfaces and ignore the points in empty space anyway.
