### ISSUE TITLE
Camera pose calibration

### ISSUE THREAD

**Issue by cygerts** [IntelVCL/Open3D#791]
I would like to perform camera calibration (perhaps with chessboard) as with openCV tutorial:
https://docs.opencv.org/3.3.0/dc/dbb/tutorial_py_calibration.html
https://docs.opencv.org/3.3.0/d7/d53/tutorial_py_pose.html

From this tutorial I obtain rotation (tvec) and translation (rvec) vectors. From rvec I create rotation matrix using Rodrigues function and add translation vector to 4th column.
So my transformation matrix looks like this:
R R R T
R R R T
R R R T
0 0 0  1
Which I use in pcd.transform. 
However it is clearly not what I wanted because the XY plane is not alligned with chessboard (and it is alligned in python example), and start of coordinate system in nowhere near the chessboard.

My question is how can I get appropriate transformation matrix in open3d world? I am also not sure why the matrix obtained from openCV tutorial would not work.

Transformation matrix looks like this:
   pcd.transform([[0.55321857, -0.82641802, 0.10479728, 6.64481418],  
                                 [0.11099627, 0.19780679, 0.9739365, 8.06095214 ],
                                 [-0.82560829, -0.52716765, 0.2011597, 36.24560899],
                                 [0, 0, 0, 1]])
Which makes some sense to me since object of interest was placed around 36~40 cm from the camera

**Comment by syncle** [comment]
How the transformation is defined? Is that the transformation w.r.t. the checker board plane or w.r.t. the camera center? Depending on the cases, you might need to try ``pcd.transform(np.linalg.inv(YOUR_TRANSFORMATION_MATRIX))``.

**Comment by syncle** [comment]
Can you check if the unit for the point cloud is the same as the unit of the transformation matrix? The scale issue may arise from this - for example point cloud is triangulated using meter unit, but the transformation matrix could be in centimeter unit. Understanding the units would avoid manual tweak to match the scales.

**Comment by cygi1989** [comment]
I think it is in the same unit but the issue still arises.

So let me explain what I am doing (or what is the tutorial doing). We find corners of the chessboard in image XY coordinates. Then I want to find transformation matrix that will convert those image points to real world coordinates, lets just assume mm scale. So I give to the solver many pais of <XYimage, XYZworld>. So for example I would like my point in the Image with X = 150, Y= 250 pix correspond to point (20,0,0) in the real world - because I know each square on the chessboard has 20 mm.
Can I calculate the transformation in open3d?

**Comment by syncle** [comment]
@cygi1989. There is linear solver in Open3D, but it is not for the specified functionality. I would recommend numpy to get the transformation matrix.

**Comment by cygi1989** [comment]
So the depth scale is gathered using ONI_PIXEL_FORMAT_DEPTH_1_MM. I then divide it by 1000 so we are in meters metric.
Than I correctly find corners of checkerboard and save their image coordinates (in pixels) to _corners_variable. Distance between corners in reality is 0.02 m (2cm). So I match the _corners_ with a matrix of new _world_corners_ I want those corners to have (so (0,0,0), (0.02, 0,0), (0.04, 0,0), etc. 

The transformation matrices I obtain are calculated using:

    ret, mtx, dist, rvec, tvec = cv2.calibrateCamera(worldcorners, corners, gray.shape[::-1], None, None)

where rvec is rotation vector and tvec is translation vector. Result is very similar if I use: cv2.solvePnP(objp, corners2, mtx, dist)
It works perfectly in OpenCV. The coordinate axis plotted bellow starts in checkerboard corner:

    imgpts, _ = cv2.projectPoints(axis, rvec, tvec, mtx, dist)
 
so I want to do the same in open3d. Firstly I get rotationMatrix:
    
    rrr,_ = cv2.Rodrigues(rvec)

Then I use pcd.transform:

    pcd.transform(np.linalg.inv([[rrr[0][0], rrr[0][1], rrr[0][2], tvec[0]],  
                                 [rrr[1][0], rrr[1][1], rrr[1][2], tvec[1],
                                 [rrr[2][0], rrr[2][1], rrr[2][2], tvec[2]],
                                 [0, 0, 0, 1]]))

and it doesnt work as stated before.

What is intriguing is that for example tvec value is [-0.05570041, -0.11792857,  2.93726789]. I would expect last coordinate to be around 0.4 since it is the distance where the checkerboard is placed (and also minimum value in depth map except from 0). 

Probably it does not make sense to paste up my code, but any help / comments would be appreciated. I assume there must be conceptually sth wrong with my approach

**Comment by cygi1989** [comment]
I am there is simply sth wrong with that concept. In OpenCV I calculate rotation and translation vector (whic sums to transformation matrix) to project points from world coordinate system onto image.
I cannot use reverse of that matrix to transform pointcloud into the desired coordinate system. Any help how to achieve that would be really helpful.

**Comment by cygerts** [comment]
The tutorial provided by openCV is doing sth different.
What we are looking for here is to find affine transformation matrix to convert set of points from rgbd image to desired positions in the world coordinate system. 
To achieve that I have obtained points from rgbd image using pick_points function from this tutorial: http://www.open3d.org/docs/tutorial/Advanced/interactive_visualization.html
In this function I select corners of the checkerboard.
Those points are matched to the desired values in the world coordinate system using Kabsch algorithm:
https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/box_dimensioner_multicam/calibration_kabsch.py

Finally I get exactly what I needed. More work is required to get automatic coordinates of checkerboard corners but that is fine for now.

![image](https://user-images.githubusercontent.com/8560577/53764377-5bbf6b00-3ecd-11e9-9e62-80094a7202c4.png)
